# Generated by Django 2.2.4 on 2019-09-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='qid',
            new_name='questions',
        ),
    ]
